export const WHITE_COLOR = '#ffffff'
export const LIGHT_GREY_COLOR = '#F2F2F2'
export const LIGHTEST_GREY_COLOR = '#F7FAFF'
export const GHOST_WHITE_COLOR = '#FAFBFF'
export const BLACK_COLOR = '#000'
export const DARK_BLUE_COLOR = '#232968'
export const LIGHT_BLUE_COLOR = '#2855FF'
export const GRAY_COLOR = '#D6D8E7'
export const LIGHT_GRAY_COLOR = '#394352'
export const DARK_GRAY_COLOR = '#262A35'
export const LIGHTEN_GRAY_COLOR = '#F4F7FF'
export const LIGHTEN_GRAY_COLOR_50 = 'rgba(244, 247, 255, 0.5)'
export const LIGHTEST_GRAY_COLOR = '#E3E4EE'
export const DARKEN_GRAY_COLOR = '#B8BBD4'
export const PALE_GRAY_COLOR = '#F6F9FF'
export const LIGHT_GREEN_COLOR = '#E6F9F2'
export const DARK_GREEN_COLOR = '#07C07E'
export const DARK_GREEN_DISABLED_COLOR = '#C0EAD9'
export const LIGHT_RED_COLOR = '#FCEDEC'
export const DARK_RED_COLOR = '#E54C40'
export const ORANGE_COLOR = '#F29D41'
export const GRAY_BLUE_COLOR = 'rgba(35, 41, 104, 0.5)'
export const DARK_GRAY_BLUE_COLOR = 'rgba(35, 41, 104, 0.7)'
export const YELLOW_INFO_RELEASE_COLOR = '#FEF7F0'
export const GEEN_INFO_APPROVE_COLOR = '#E7F9F3'
export const RED_INFO_REJECTED_COLOR = '#FDEEEC'
export const LIGHTEST_BLUE_COLOR = '#F9FBFF'

export const LIGHT_BLUE_DISABLED_COLOR = '#E5EAFF'
export const DARK_RED_DISABLED_COLOR = '#F5B7B3'

export const SIDEBAR_BACKGROUND_COLOR = WHITE_COLOR
export const SIDENAV_BORDER_COLOR = GRAY_COLOR

export const TEXTFIELD_COLOR = DARK_BLUE_COLOR
export const ERROR_COLOR = '#f44336'
