export const BILL_VIEW_TITLE = 'Bill details'
export const VIEW_MAIN_SUBTITLE = 'General info'
export const VIEW_ADDITIONAL_INFO = 'Additional info'
export const COST_LINES_TITLE = 'COST LINES'
export const COST_ITEMS_TITLE = 'COST ITEMS'
export const LINE_ITEMS_TITLE = 'Line items'
export const INTERNAL_NOTES_TITLE = 'INTERNAL NOTES'
export const FLAT_RATE_TITLE = 'Flat rate'
export const OPPORTUNITY_VIEW_TITLE = 'Opportunity details'

export const SCHEDULE_VIEW_TITLE = 'Scheduled item details'
export const PURCHASE_ORDER_VIEW_TITLE = 'Purchase order details'
export const CHANGE_ORDER_VIEW_TITLE = 'Change order details'
export const PROPOSAL_VIEW_TITLE = 'Proposal details'
export const ACTIVITY_VIEW_TITLE = 'Activity details'
export const BID_REQUEST_VIEW_TITLE = 'Bid request details'
